/racebot/controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    right_rear_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_rear_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_front_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_front_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_front_steering_position_controller:
      type: position_controllers/JointGroupPositionController

    left_front_steering_position_controller:
      type: position_controllers/JointGroupPositionController

/racebot/joint_state_broadcaster:
  ros__parameters: {}

/racebot/right_rear_velocity_controller:
  ros__parameters:
    joints: 
      - right_rear_wheel_joint

/racebot/left_rear_velocity_controller:
  ros__parameters:
    joints: 
      - left_rear_wheel_joint

/racebot/right_front_velocity_controller:
  ros__parameters:
    joints: 
      - right_front_wheel_joint

/racebot/left_front_velocity_controller:
  ros__parameters:
    joints: 
      - left_front_wheel_joint

/racebot/right_front_steering_position_controller:
  ros__parameters:
    joints: 
      - right_steering_hinge_joint

/racebot/left_front_steering_position_controller:
  ros__parameters:
    joints: 
      - left_steering_hinge_joint

