/racebot/controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    right_rear_velocity_controller:
      type: velocity_controllers/JointVelocityController

    left_rear_velocity_controller:
      type: velocity_controllers/JointVelocityController

    right_front_velocity_controller:
      type: velocity_controllers/JointVelocityController

    left_front_velocity_controller:
      type: velocity_controllers/JointVelocityController

    right_front_steering_position_controller:
      type: position_controllers/JointPositionController

    left_front_steering_position_controller:
      type: position_controllers/JointPositionController

/racebot/joint_state_broadcaster:
  ros__parameters: {}

/racebot/right_rear_velocity_controller:
  ros__parameters:
    joint: right_rear_wheel_joint

/racebot/left_rear_velocity_controller:
  ros__parameters:
    joint: left_rear_wheel_joint

/racebot/right_front_velocity_controller:
  ros__parameters:
    joint: right_front_wheel_joint

/racebot/left_front_velocity_controller:
  ros__parameters:
    joint: left_front_wheel_joint

/racebot/right_front_steering_position_controller:
  ros__parameters:
    joint: right_steering_hinge_joint

/racebot/left_front_steering_position_controller:
  ros__parameters:
    joint: left_steering_hinge_joint

